### PR TITLE
Add esm output and ignore dist

### PR DESCRIPTION
**Pull request by TrySound**
Committing compiled files in git is usually not the best way to
distribute library. For distributing `umd` files it would be more
effecient to use cdn or services like [unpkg.com](https://unpkg.com/react-input-mask).
It's also better because pulling these files from git repo also requires
user actions and own services so we just move this responsibility to
`npm` (in case of unpkg).

In this diff I removed `dist` directory from git to reduce confusion for
contributors and make publishing less verbose.

I moved all compiled files in `dist` directory and added `umd` prefix to
not minified bundle. Also I added `esm` output. So `dist` directory now
looks very nice and intuitive for consumers.

```
react-input-mask.cjs.js
react-input-mask.esm.js
react-input-mask.min.js
react-input-mask.umd.js
```

### CODE REVIEW

**Comment by TrySound** [comment]
If you want I can do not add `umd` suffix to not introduce breaking change. It's also usable pattern.
https://unpkg.com/react-beautiful-dnd@7.1.2/dist/

**Comment by TrySound** [comment]
Can providing a link like this in readme help? It selects version automatically.
[react-input-mask.js](https://unpkg.com/react-input-mask/dist/react-input-mask.js)

The problem with master version is that it can be too different from latest published and users will be confused about it. This version can be also broken for some tricky reason or just lack of time. So I wouldn't rely on it in any case.

**Comment by sanniassin** [comment]
No confusion, I always keep it in sync with the latest npm release.

**Comment by TrySound** [comment]
Okay. Can we keep only `react-input-mask.umd.js` here and ignore another bundles?

**Comment by sanniassin** [comment]
As I see, there are two "conventions" in structures. The first one, which is widely used in React ecosystem. is more convenient for developers as you don't need to care whether you should commit builds or not. The second one, which is often used by libraries like [moment](https://github.com/moment/moment/) or [axios](https://github.com/axios/axios), is more convenient for some users for the reasons I mentioned earlier.

Since `react-input-mask` belongs to the React ecosystem and, I guess, it's very rare to use React without a module bundler these days, I need to think again thoroughly. Perhaps, removing prebuilt versions from this repo is a good idea.

**Comment by TrySound** [comment]
So what do you decide? I can do not introduce breaking changes in this PR if you want.

**Comment by sanniassin** [comment]
I decided to add `lib` and `dist` to .gitignore and keep the structure unchanged.

Could you explain why do you need esm? Is there any case when cjs build isn't suitable?

**Comment by TrySound** [comment]
esm is easier to handle statically and output of it is a bit smaller since we don't need to wrap it with cjs runtime.

**Comment by TrySound** [comment]
Also esm bundle will better fit to browser modules.

**Comment by TrySound** [comment]
cjs becoming more and more useless. Most popular bundler uses esm builds, cjs is required only for running in node and that's just because `esm` loader doesn't work everywhere yet.

That's because babel handle it differently. I'll give my tooth rollup bundles work perfectly.

**Comment by TrySound** [comment]
By the way you don't need .npmignore with files field.

**Comment by sanniassin** [comment]
Is there any possible production environment where cjs won't work, but esm will?

**Comment by TrySound** [comment]
Oh, I get it what was an issue. Commonjs users should not consume es modules. They should just disable it. This is not the only project where they can catch this. Hundreds of projects are broken for them because they can't configure webpack.

**Comment by TrySound** [comment]
Just take a look that everybody is happy with it. I will handle an issue if you will have any.
https://github.com/atlassian/react-beautiful-dnd/blob/master/package.json#L21
https://github.com/renatorib/react-powerplug/blob/master/package.json#L8
https://github.com/recharts/recharts/blob/master/package.json#L6
https://github.com/bvaughn/react-virtualized/blob/master/package.json#L9

**Comment by TrySound** [comment]
We should adopt esm and should teach users to consume it. Without changes there won't be a progress. And it's related to any small project. Everybody should be involved to fix things. And now esm via `module` field is one of those fixes.

**Comment by sanniassin** [comment]
In short, package with esm in package.json is more susceptible to imperfect environment configuration.

Being easy to use is the main idea behind `react-input-mask`. It still supports IE8 and React 0.13 with literally no overhead in project complexity. So, if there are no strong advantages in user experience or project maintainability, I'll keep the solution which works better across wide variety of environments.

It turns into discussion about personal preferences, so I'm closing this PR.

**Comment by TrySound** [comment]
I just care about ecosystem and doing my best to keep everything consistent and efficient.

**Comment by TrySound** [comment]
Stop supporting legacy is a good option for major releases by the way.

**Comment by sanniassin** [comment]
I understand. I might reconsider that when React itself adds esm build.

**Pull request closed without merging**
