### PR TITLE
Proxy focus and blur methods

### PR DESCRIPTION
**Pull request by vslinko**

### CODE REVIEW

**Comment by sanniassin** [comment]
@vslinko It would be nice to have a description of this PR and it's benefits.

**Comment by vslinko** [comment]
You could see conversation on this PR https://github.com/insin/react-maskedinput/pull/52

**Comment by sanniassin** [comment]
@vslinko Won't merge. While i can understand benefits it's not a good architectural decision to simulate DOM element because it's not and it may confuse if you can focus but can't get value or set selection. So i recommend to use ```findDOMNode``` on react-input-mask component and interact with real HTMLInputElement.

**Comment by vslinko** [comment]
It seems like you're right. I just forgot that I can use `findDOMNode` on the composite component. Closing the PR.

**Pull request closed without merging**
