### PR TITLE
Fix focus input when mask changes

### PR DESCRIPTION
**Pull request by ngryman**
Replaces #153.

### CODE REVIEW

**Comment by sanniassin** [comment]
Thanks a lot. Will release an update soon.

**Comment by sanniassin** [comment]
@ngryman Released 2.0.4

**Comment by myagkou** [comment]
This is an incomplete fix because of a deferred input selection update.
https://github.com/sanniassin/react-input-mask/blob/2.0.4/src/index.js#L279

There would be the same reported behaviour if I have changed focus to a field before deferred code works.

**Comment by myagkou** [comment]
I may provide a PR fixing the issue but I see the current codebase is far ahead of the `v2.0.4` release.

**Pull request merged**
