### PR TITLE
Add render prop support

### PR DESCRIPTION
**Pull request by denisborovikov**
```jsx
import React from 'react';
import InputMask from 'react-input-mask';
import styled from 'styled-components';

const StyledInput = styled.input`
  border-color: red;
`;

class Input extends React.Component {
  render() {
    return <InputMask mask="99999-9999" render={(ref, props) => <StyledInput innerRef={ref} {...props} />} />;
  }
}
```
I'm not familiar with test writting. Help is appreciated.

### CODE REVIEW

**Comment by TrySound** [comment]
I would use children as function variant to be in sync with react itself (new context api). It's also more readable with some nesting inside such function.

**Comment by sanniassin** [comment]
@denisborovikov @TrySound I'm working on it right now, stay tuned.

**Comment by denisborovikov** [comment]
Thanks, guys, just wanted to share the idea, glad you're on it already.

**Comment by sanniassin** [comment]
Using `children` or `render` function might lead to confusion on what input — parent or child — should you listen to events. What do you think about this syntax with `inputComponent` prop?
```jsx
import React from 'react';
import InputMask from 'react-input-mask';
import TextField from '@material-ui/core/TextField';

class Input extends React.Component {
  state = {
    value: ''
  }

  onChange = (event) => {
    this.setState({
      value: event.target.value
    });
  }

  render() {
    return <InputMask
      inputComponent={TextField}
      mask="99999-9999"
      value={this.state.value}
      onChange={this.onChange}
    />;
  }
}
```

The problem with it is a possibility to get a conflict between react-input-mask's and child's properties. For example, TextField in material-ui has its own `inputRef` prop which is impossible to use with this syntax.

**Comment by denisborovikov** [comment]
As for me, I don't see any confusion here. But you may allow using only [prop getters](https://github.com/paypal/downshift#render-prop-function) inside the render prop.

Something like 
```jsx
<InputMask
    mask="99999-9999"
    value={this.state.value}
    onChange={this.onChange}
>
 ({ getInputProps }) => <input {...getInputProps()} />
</InputMask>
```

**Comment by sanniassin** [comment]
Might work, but it will be great if we can find a simpler solution. To make it clear for someone who isn't familiar with `react-input-mask`, but has to fix an error in this code.

**Comment by TrySound** [comment]
You may write a descriptive changelog with diff in examples like this

```diff
- <InputMask />
+ <InputMask>
+   {() => null}
+ </InputMask>
```

**Comment by sanniassin** [comment]
@denisborovikov @TrySound Implemented support for `children` function.

**Comment by TrySound** [comment]
Cool

**Comment by TrySound** [comment]
Ah, I see findDOMNode. Not cool. It won't work with async react and probably will be deprecated soon.

**Comment by sanniassin** [comment]
Will work around this when it happens :)

**Comment by sanniassin** [comment]
@TrySound Any ideas how to find input node inside children without findDOMNode and wrapping input into another node?

**Comment by sanniassin** [comment]
As I see both react-powerplug and react-measure attach to the actual DOM node with bind or measureRef and can't be used with functional components, can they?

**Comment by TrySound** [comment]
Do you expect any kind of abstraction there? For this purpose was introduced `React.forwardRef` helper. So it's not a problem.

**Comment by denisborovikov** [comment]
I still think prop getter is a good pattern that could fit into this case perfectly. More about the pattern [here](https://blog.kentcdodds.com/how-to-give-rendering-control-to-users-with-prop-getters-549eaef76acf). It allows to combine parent and child handlers.

```jsx
<InputMask
    mask="99999-9999"
    value={this.state.value}
    onChange={this.onChange}
>
 ({ getInputProps }) => <input {...getInputProps({ onChange: this.onChangeHalndler})} />
</InputMask>
```

Clarification of not using some props seems weird for me and definitely not a simpler solution.

**Comment by TrySound** [comment]
I don't think somebody need to apply more than one callback here. It's better to use InputMask as proxy and listen only it. Children as function should be used only for changing element (from material ui for example), styling and not related to masking stuff.

**Comment by TrySound** [comment]
I don't think such components are supposed to be customized with masks. They hide dom element so it's not our problem.

**Comment by TrySound** [comment]
For things which exposes innerRef/componentRef bind may be passed explicitly without spread.

**Comment by sanniassin** [comment]
But it also might be the main concern to pass component inside react-input-mask (#80). Let's make it more universal for now and see on the actual use cases. While It's an experimental feature and it's compatible with all current versions of React, I think it's fine to rely on findDOMNode until we get some statistics or until we find out a better alternative to findDOMNode.

**Pull request closed without merging**
