### PR TITLE
Ability to customize rules

### PR DESCRIPTION
**Pull request by sapegin**
I’ll update the docs if you like these changes.

### CODE REVIEW

**Comment by sapegin** [comment]
Hey @sanniassin, what can I do to make it merged?

**Comment by sanniassin** [comment]
@sapegin Merged, thank you! It's really useful feature, but i have no time to support this project at this moment, so docs update will be very helpful.

**Comment by sapegin** [comment]
Thanks, I’ll update the docs too.

**Comment by sapegin** [comment]
Done, sorry for the delay.

**Comment by sanniassin** [comment]
@sapegin I've update it with my own docs already, but thanks anyway :)

**Pull request merged**
